language: rust
sudo: false
matrix:
  fast_finish: true
  include:
  - rust: nightly
    env: FEATURES="--features nightly"
  - rust: beta
  - rust: stable
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - build-essential
    - curl
    - expect
    - cmake
    - pkg-config
    - zlib1g-dev
    - libgit2-dev
    - libssh2-1-dev
    - libssl-dev
    sources:
    - kalakris-cmake
cache:
  apt: true
  directories:
  - target/debug/deps
  - target/debug/build
  - target/release/deps
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
  - master
  - develop
script:
- |
  cargo test -- --test-threads=1 &&
  cargo test --release -- --test-threads=1
before_script:
- 'gem install redis'
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
- |
  if [[ "$TRAVIS_RUST_VERSION" != stable ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo install cargo-update
    cargo install-update -a
  fi
- |
  ./tests/scripts/install_redis_centralized.sh &&
  redis-server --daemonize yes
- "./tests/scripts/install_redis_clustered.sh"
after_success:
- redis-cli -p 6379 shutdown
- "$TRAVIS_BUILD_DIR/tests/tmp/redis_cluster_$REDIS_VERSION/redis-$REDIS_VERSION/utils/create-cluster/create-cluster stop"
- |
  if [[ "$TRAVIS_RUST_VERSION" != stable ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
env:
  global:
  - RUST_BACKTRACE=1
  - REDIS_VERSION=5.0.5
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - PATH=$PATH:$TRAVIS_BUILD_DIR/tests/tmp/redis-$REDIS_VERSION/src